name: Create Release

on:
  push:
    branches:
      - master
    paths:
      - 'website/package.json'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: jokelbaf/pnpm-release@master
        with:
          package_path: website/package.json
          cliff_template: https://cdn.jokelbaf.dev/blog/cliff-template.toml
